# Generated by Django 5.0.2 on 2024-03-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_feedback_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='feedback_text',
        ),
    ]
