# Generated by Django 5.0.2 on 2024-03-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_feedback_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
