# Generated by Django 5.0.2 on 2024-04-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_feedback_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
