# Generated by Django 5.0.2 on 2024-04-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_category_alter_issue_category_issueadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('fee_issues', 'Fee Issues'), ('guidance_and_counselling', 'Guidance and Counselling'), ('accommodation', 'Accommodation'), ('exam_issues', 'Exam Issues'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.issueadmin'),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='issue_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.issueadmin'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
