# Generated by Django 5.0.2 on 2024-04-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_issue_category_issue_issue_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuehistory',
            name='issue_admin',
        ),
    ]
