# Generated by Django 5.0.2 on 2024-04-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_issuehistory_issue_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueadmin',
            name='user',
        ),
        migrations.AddField(
            model_name='issueadmin',
            name='role',
            field=models.CharField(choices=[('healthcare', 'Healthcare'), ('fee_issues', 'Fee Issues'), ('guidance_and_counselling', 'Guidance and Counselling'), ('accommodation', 'Accommodation'), ('exam_issues', 'Exam Issues'), ('others', 'Others')], default='Admin', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
